[package]
name = "openhub_bo_qr"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false
description = "Native extension of the openhub-bo-qr Ruby gem"

[lib]
name = "openhub_bo_qr"
crate-type = ["cdylib"]

[dependencies]
magnus = "0.9"
openhub-core = { path = "vendor/openhub-core" }
openhub-qr = { path = "vendor/openhub-qr" }

