[package]
name = "openhub-bo-fx-wasm"
description = "WASM module of the @openhub-bo/fx npm package"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "openhub_bo_fx_wasm"
crate-type = ["cdylib"]

[dependencies]
openhub-bo-core = { path = "../../../../crates/openhub-bo-core" }
openhub-bo-fx = { path = "../../../../crates/openhub-bo-fx" }
wasm-bindgen = "0.2"
