[package]
name = "openhub_bo_accounts"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false
description = "Native extension of the openhub-bo-accounts Ruby gem"

[lib]
name = "openhub_bo_accounts"
crate-type = ["cdylib"]

[dependencies]
magnus = "0.9"
openhub-bo-core = { path = "vendor/openhub-bo-core" }
openhub-bo-accounts = { path = "vendor/openhub-bo-accounts" }

