# frozen_string_literal: true

# Build tools only: precompiled gems are built with `bundle exec rake native:<platform> gem`.
source "https://rubygems.org"

gem "minitest", "~> 5.25"
gem "rake", "~> 13.2"
gem "rake-compiler", "~> 1.3"
gem "rb_sys", "~> 0.9.124"
