# frozen_string_literal: true

require_relative "../support/native_gem"

GEMSPEC = Gem::Specification.load(File.expand_path("openhub-bo-payouts.gemspec", __dir__))

NativeGemTasks.define(
  gem_dir: __dir__,
  pkg: "payouts",
  crates: ["openhub-core", "openhub-payouts"],
  gemspec: GEMSPEC
)
