# frozen_string_literal: true

require_relative "../support/native_gem"

NativeGemTasks.define(
  gem_dir: __dir__,
  pkg: "payouts",
  crates: ["openhub-bo-core", "openhub-bo-payouts"],
  gemspec_path: File.expand_path("openhub-bo-payouts.gemspec", __dir__)
)
