[package]
name = "openhub-bo-accounts-wasm"
description = "WASM module of the @openhub-bo/accounts npm package"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "openhub_bo_accounts_wasm"
crate-type = ["cdylib"]

[dependencies]
openhub-core = { path = "../../../../crates/openhub-core" }
openhub-accounts = { path = "../../../../crates/openhub-accounts" }
wasm-bindgen = "0.2"
