[package]
name = "openhub-bo-payouts-wasm"
description = "WASM module of the @openhub-bo/payouts npm package"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "openhub_bo_payouts_wasm"
crate-type = ["cdylib"]

[dependencies]
openhub-bo-core = { path = "../../../../crates/openhub-bo-core" }
openhub-bo-payouts = { path = "../../../../crates/openhub-bo-payouts" }
wasm-bindgen = "0.2"
